import { ArrowLeft } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import type { PublicArticle } from "@/lib/public-data";

export function PopularArticles({ articles }: { articles: PublicArticle[] }) {
  const [lead, ...rest] = articles;
  if (!lead) return null;
  return <section className="content-auto bg-(--public-paper-deep)"><div className="mx-auto max-w-360 px-4 py-14 md:px-7 md:py-20"><div className="editorial-rule border-b border-(--border-strong) pb-5"><p className="editorial-kicker">انتخاب مخاطبان</p><h2 className="mt-2 text-[27px] font-black tracking-[-.04em] text-(--public-ink) sm:text-[32px]">پرمخاطب‌های این هفته</h2></div><div className="mt-9 grid gap-8 lg:grid-cols-[1.08fr_.92fr]">
    <article className="group overflow-hidden rounded-[22px] bg-white shadow-[0_18px_50px_rgba(16,42,58,.07)]"><Link href={`/articles/${lead.slug}`} className="relative block aspect-16/9 overflow-hidden"><Image src={lead.image} alt="" fill sizes="(max-width:1024px) 100vw, 52vw" className="object-cover transition duration-700 group-hover:scale-[1.035]"/><span className="absolute right-5 top-5 grid size-13 place-items-center rounded-full bg-(--editorial-coral) font-mono text-xl font-black text-white">۱</span></Link><div className="p-6 sm:p-7"><Link href={`/categories/${lead.categorySlug}`} className="text-[13px] font-black text-(--editorial-coral)">{lead.category.name}</Link><Link href={`/articles/${lead.slug}`}><h3 className="mt-2 text-[23px] font-black leading-10 tracking-[-.035em] text-(--public-ink) group-hover:text-(--editorial-coral)">{lead.title}</h3></Link><p className="mt-3 text-[15px] leading-7 text-(--text-secondary)">{lead.excerpt}</p><Link href={`/articles/${lead.slug}`} className="mt-5 inline-flex min-h-11 items-center gap-1.5 text-[13px] font-black text-(--editorial-coral)">مطالعه مطلب <ArrowLeft size={14}/></Link></div></article>
    <ol className="divide-y divide-(--border-strong) border-y border-(--border-strong)">{rest.map((article, index) => <li key={article.id} className="group grid grid-cols-[54px_minmax(0,1fr)] gap-4 py-5"><span className="font-mono text-[28px] font-black tracking-[-.08em] text-(--text-faint)">{(index + 2).toLocaleString("fa-IR", { minimumIntegerDigits: 2 })}</span><div><Link href={`/categories/${article.categorySlug}`} className="text-[13px] font-black text-(--editorial-coral)">{article.category.name}</Link><Link href={`/articles/${article.slug}`}><h3 className="mt-1.5 text-[17px] font-black leading-8 text-(--public-ink) group-hover:text-(--editorial-coral)">{article.title}</h3></Link><p className="mt-2 text-[13px] text-(--text-muted)">{article.author.name} · {article.views.toLocaleString("fa-IR")} بازدید</p></div></li>)}</ol>
  </div></div></section>;
}
