import { BriefcaseBusiness, Camera, Code2, PenLine, Send } from "lucide-react";
import Link from "next/link";

const groups = [
  { title: "مجله", links: [["درباره ما", "/about"], ["تماس با ما", "/contact"], ["نویسندگان", "/authors"]] },
  { title: "محتوا", links: [["آخرین مقالات", "/articles"], ["محبوب‌ترین مطالب", "/articles?sort=popular"], ["دسته‌بندی‌ها", "/categories"], ["برچسب‌ها", "/tags"]] },
];

export function PublicFooter() {
  return <footer className="border-t border-(--on-dark-border) bg-(--brand-navy) text-white"><div className="mx-auto grid max-w-360 gap-10 px-4 py-14 sm:grid-cols-2 md:px-7 lg:grid-cols-4"><div><Link href="/" className="inline-flex items-center gap-3"><span className="grid size-11 place-items-center rounded-full bg-white/10 text-white"><PenLine size={18}/></span><strong className="text-[18px] font-black">تک‌نما</strong></Link><p className="mt-5 max-w-xs text-[14px] leading-7 text-(--text-on-dark-muted)">روایت دقیق و مستقل از فناوری، محصول و آدم‌هایی که آینده دیجیتال را می‌سازند.</p><Link href="/admin/dashboard" className="mt-5 inline-flex min-h-10 items-center rounded-full border border-white/15 px-4 text-[12px] font-bold text-white/70 hover:border-white/40 hover:text-white">ورود به نسخه نمایشی اتاق خبر</Link></div>{groups.map((group) => <nav key={group.title} aria-label={group.title}><h3 className="text-[14px] font-black">{group.title}</h3><div className="mt-4 space-y-2">{group.links.map(([label, href]) => <Link key={href} href={href} className="flex min-h-10 items-center text-[14px] text-(--text-on-dark-muted) hover:text-white">{label}</Link>)}</div></nav>)}<div><h3 className="text-[14px] font-black">همراه ما باشید</h3><p className="mt-3 text-[13px] leading-6 text-(--text-on-dark-muted)">شبکه‌های اجتماعی هم‌زمان با انتشار رسمی فعال می‌شوند.</p><div className="mt-4 flex gap-2"><Social icon={Camera} label="اینستاگرام"/><Social icon={Send} label="تلگرام"/><Social icon={BriefcaseBusiness} label="لینکدین"/><Social icon={Code2} label="گیت‌هاب"/></div></div></div><div className="border-t border-white/10"><div className="mx-auto flex max-w-360 flex-col gap-3 px-4 py-5 text-[13px] text-(--text-on-dark-muted) sm:flex-row sm:items-center md:px-7"><p>© ۱۴۰۵ تک‌نما؛ تمام حقوق محفوظ است.</p><div className="sm:mr-auto"><Link href="/privacy" className="hover:text-white">حریم خصوصی</Link><span className="mx-3">•</span><Link href="/terms" className="hover:text-white">قوانین استفاده</Link></div></div></div></footer>;
}

function Social({ icon: Icon, label }: { icon: typeof Camera; label: string }) { return <span aria-label={`${label}؛ به‌زودی`} title={`${label}؛ به‌زودی`} className="grid size-11 place-items-center rounded-full border border-white/15 text-(--text-on-dark-muted)"><Icon size={16}/></span>; }
