"use client";
import { Ban, CheckCircle2, Clock3, MessageSquareText } from "lucide-react";
import { useMemo, useState } from "react";
import { StatCard } from "@/components/dashboard/stat-card";
import { Pagination } from "@/components/ui/pagination";
import { mockComments, type CommentStatus, type MagazineComment } from "@/lib/comments-data";
import { commentsService } from "@/lib/comments-service";
import { CommentBulkActions } from "./comment-bulk-actions";
import { CommentDetailDialog, DeleteCommentDialog } from "./comment-dialogs";
import { CommentsEmptyState } from "./comments-empty-state";
import { CommentsList } from "./comments-list";
import { CommentsToolbar, type CommentSort, type DateFilter } from "./comments-toolbar";

const pageSize = 8;
export function CommentsManager() {
  const [comments, setComments] = useState(mockComments); const [query, setQuery] = useState(""); const [status, setStatus] = useState<"all" | CommentStatus>("all"); const [article, setArticle] = useState("all"); const [author, setAuthor] = useState("all"); const [date, setDate] = useState<DateFilter>("all"); const [sort, setSort] = useState<CommentSort>("newest"); const [page, setPage] = useState(1); const [selected, setSelected] = useState<Set<string>>(new Set()); const [preview, setPreview] = useState<MagazineComment | null>(null); const [deleteIds, setDeleteIds] = useState<string[]>([]); const [notice, setNotice] = useState("");
  const filtered = useMemo(() => { const term = query.trim().toLocaleLowerCase("fa"); const now = new Date("2026-09-08T23:59:59Z").getTime(); const limits: Record<DateFilter, number> = { all: Infinity, today: 86400000, week: 7 * 86400000, month: 30 * 86400000 }; return comments.filter((item) => { const searchMatch = !term || [item.content, item.commenter.name, item.commenter.email].some((value) => value.toLocaleLowerCase("fa").includes(term)); const dateMatch = date === "all" || now - new Date(item.createdAt).getTime() <= limits[date]; return searchMatch && dateMatch && (status === "all" || item.status === status) && (article === "all" || item.article.id === article) && (author === "all" || item.author.id === author); }).sort((a, b) => sort === "likes" ? b.likes - a.likes : sort === "oldest" ? +new Date(a.createdAt) - +new Date(b.createdAt) : +new Date(b.createdAt) - +new Date(a.createdAt)); }, [article, author, comments, date, query, sort, status]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / pageSize)); const safePage = Math.min(page, pageCount); const start = (safePage - 1) * pageSize; const visible = filtered.slice(start, start + pageSize); const allVisibleSelected = visible.length > 0 && visible.every((item) => selected.has(item.id));
  const showNotice = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(""), 2600); };
  const reset = () => { setQuery(""); setStatus("all"); setArticle("all"); setAuthor("all"); setDate("all"); setSort("newest"); setPage(1); };
  const toggle = (id: string) => setSelected((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });
  const toggleAll = () => setSelected((current) => { const next = new Set(current); visible.forEach((item) => allVisibleSelected ? next.delete(item.id) : next.add(item.id)); return next; });
  const updateOne = async (comment: MagazineComment, nextStatus: CommentStatus) => { const updated = await commentsService.updateStatus(comment, nextStatus); setComments((items) => items.map((item) => item.id === updated.id ? updated : item)); setPreview((item) => item?.id === updated.id ? updated : item); showNotice(statusNotice(nextStatus, false)); };
  const updateSelected = async (nextStatus: CommentStatus) => { const updated = await commentsService.updateMany(comments, selected, nextStatus); setComments(updated); setSelected(new Set()); showNotice(statusNotice(nextStatus, true)); };
  const confirmDelete = async () => { const ids = new Set(deleteIds); setComments(await commentsService.remove(comments, ids)); setSelected((current) => new Set([...current].filter((id) => !ids.has(id)))); if (preview && ids.has(preview.id)) setPreview(null); showNotice(deleteIds.length > 1 ? "دیدگاه‌های انتخاب‌شده حذف شدند." : "دیدگاه حذف شد."); setDeleteIds([]); };
  const stats = [{ label: "کل دیدگاه‌ها", value: comments.length, trend: "۱۶٪", icon: MessageSquareText }, { label: "در انتظار بررسی", value: comments.filter((item) => item.status === "pending").length, trend: "۵٪", icon: Clock3 }, { label: "تأیید شده", value: comments.filter((item) => item.status === "approved").length, trend: "۱۲٪", icon: CheckCircle2, accent: true }, { label: "گزارش‌شده / اسپم", value: comments.filter((item) => item.status === "spam").length, trend: "۲٪", icon: Ban }];
  const changeFilter = <T,>(setter: (value: T) => void) => (value: T) => { setter(value); setPage(1); };
  return <><section className="mt-6 grid grid-cols-2 gap-3 xl:grid-cols-4">{stats.map((item) => <StatCard key={item.label} label={item.label} value={item.value.toLocaleString("fa-IR")} trend={item.trend} icon={item.icon} accent={item.accent}/>)}</section><div className="mt-4 space-y-3"><CommentsToolbar query={query} status={status} article={article} author={author} date={date} sort={sort} count={filtered.length} onQuery={changeFilter(setQuery)} onStatus={changeFilter(setStatus)} onArticle={changeFilter(setArticle)} onAuthor={changeFilter(setAuthor)} onDate={changeFilter(setDate)} onSort={changeFilter(setSort)} onReset={reset}/><CommentBulkActions count={selected.size} onApprove={() => updateSelected("approved")} onReject={() => updateSelected("rejected")} onSpam={() => updateSelected("spam")} onDelete={() => setDeleteIds([...selected])} onClear={() => setSelected(new Set())}/><section className="overflow-visible rounded-(--radius) border border-(--border) bg-white">{visible.length ? <><CommentsList comments={visible} selectedIds={selected} allVisibleSelected={allVisibleSelected} onSelect={toggle} onSelectAll={toggleAll} onPreview={setPreview} onStatus={updateOne} onDelete={(comment) => setDeleteIds([comment.id])}/><Pagination page={safePage} pageCount={pageCount} start={start + 1} end={Math.min(start + pageSize, filtered.length)} total={filtered.length} onPageChange={setPage} itemLabel="دیدگاه" ariaLabel="صفحه‌بندی دیدگاه‌ها"/></> : <CommentsEmptyState hasComments={comments.length > 0} onReset={reset}/>}</section></div><CommentDetailDialog key={preview?.id ?? "closed-comment"} comment={preview} parent={comments.find((item) => item.id === preview?.parentId)} onClose={() => setPreview(null)} onStatus={(nextStatus) => { if (preview) updateOne(preview, nextStatus); }} onDelete={() => { if (preview) setDeleteIds([preview.id]); }}/><DeleteCommentDialog open={deleteIds.length > 0} count={deleteIds.length} onCancel={() => setDeleteIds([])} onConfirm={confirmDelete}/>{notice && <div role="status" className="fixed bottom-5 left-5 z-[95] rounded-(--radius-sm) bg-(--brand-navy) px-4 py-3 text-[13px] font-bold text-white shadow-[0_10px_30px_rgba(16,35,49,.2)]">{notice}</div>}</>;
}
function statusNotice(status: CommentStatus, plural: boolean) { const subject = plural ? "دیدگاه‌های انتخاب‌شده" : "دیدگاه"; return status === "approved" ? `${subject} تأیید ${plural ? "شدند" : "شد"}.` : status === "rejected" ? `${subject} رد ${plural ? "شدند" : "شد"}.` : `${subject} به‌عنوان اسپم علامت‌گذاری ${plural ? "شدند" : "شد"}.`; }

