import { Search, SlidersHorizontal, X } from "lucide-react";
import { commentArticles, commentAuthors, type CommentStatus } from "@/lib/comments-data";
export type CommentSort = "newest" | "oldest" | "likes"; export type DateFilter = "all" | "today" | "week" | "month";
const selectClass = "h-10 min-w-0 rounded-(--radius-sm) border border-(--border) bg-white px-3 text-[13px] font-bold text-(--text-secondary) outline-none transition-colors focus:border-(--focus-border)";
export function CommentsToolbar({ query, status, article, author, date, sort, count, onQuery, onStatus, onArticle, onAuthor, onDate, onSort, onReset }: { query: string; status: "all" | CommentStatus; article: string; author: string; date: DateFilter; sort: CommentSort; count: number; onQuery: (value: string) => void; onStatus: (value: "all" | CommentStatus) => void; onArticle: (value: string) => void; onAuthor: (value: string) => void; onDate: (value: DateFilter) => void; onSort: (value: CommentSort) => void; onReset: () => void }) {
  const active = query || status !== "all" || article !== "all" || author !== "all" || date !== "all";
  return <section className="rounded-(--radius) border border-(--border) bg-white p-3 sm:p-4"><div className="flex flex-col gap-3"><label className="flex h-10 items-center gap-2 rounded-(--radius-sm) border border-(--border) bg-(--surface-subtle) px-3 text-(--muted) focus-within:border-(--border-strong) focus-within:bg-white"><Search size={16}/><span className="sr-only">جستجو در دیدگاه‌ها</span><input value={query} onChange={(event) => onQuery(event.target.value)} placeholder="جستجو در دیدگاه‌ها..." className="h-full w-full bg-transparent text-[14px] outline-none"/>{query && <button type="button" onClick={() => onQuery("")} aria-label="پاک‌کردن جستجو"><X size={14}/></button>}</label><div className="grid grid-cols-2 gap-2 md:grid-cols-3 xl:grid-cols-5"><select value={status} onChange={(event) => onStatus(event.target.value as "all" | CommentStatus)} aria-label="فیلتر وضعیت" className={selectClass}><option value="all">همه وضعیت‌ها</option><option value="pending">در انتظار بررسی</option><option value="approved">تأیید شده</option><option value="rejected">رد شده</option><option value="spam">اسپم</option></select><select value={article} onChange={(event) => onArticle(event.target.value)} aria-label="فیلتر مقاله" className={selectClass}><option value="all">همه مقاله‌ها</option>{commentArticles.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><select value={author} onChange={(event) => onAuthor(event.target.value)} aria-label="فیلتر نویسنده" className={selectClass}><option value="all">همه نویسندگان</option>{commentAuthors.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={date} onChange={(event) => onDate(event.target.value as DateFilter)} aria-label="فیلتر تاریخ" className={selectClass}><option value="all">همه تاریخ‌ها</option><option value="today">امروز</option><option value="week">۷ روز اخیر</option><option value="month">۳۰ روز اخیر</option></select><select value={sort} onChange={(event) => onSort(event.target.value as CommentSort)} aria-label="مرتب‌سازی" className={`${selectClass} col-span-2 md:col-span-1`}><option value="newest">جدیدترین</option><option value="oldest">قدیمی‌ترین</option><option value="likes">بیشترین لایک</option></select></div></div><div className="mt-3 flex min-h-7 items-center justify-between border-t border-(--border-subtle) pt-3 text-[12px] text-(--text-muted)"><span className="flex items-center gap-1.5"><SlidersHorizontal size={13}/>{count.toLocaleString("fa-IR")} دیدگاه</span>{active && <button type="button" onClick={onReset} className="font-bold text-(--accent)">پاک‌کردن فیلترها</button>}</div></section>;
}

