import { SearchX } from "lucide-react";
import Link from "next/link";
import { ArticleCardSkeleton } from "@/components/skeletons/article-card-skeleton";
import { NewsletterSkeleton, PaginationSkeleton } from "@/components/skeletons/public-shared-skeletons";
import { LoadingStatus, Skeleton } from "@/components/ui/skeleton";
import type { PublicCategory } from "@/lib/public-data";

export function InitialSearchState({ categories }: { categories: PublicCategory[] }) {
  return <section className="mx-auto max-w-4xl px-4 py-12 text-center md:px-7 md:py-16"><h2 className="text-lg font-black text-(--text-strong)">جست‌وجوی محتوای مجله</h2><p className="mx-auto mt-2 max-w-xl text-[13px] leading-6 text-(--text-muted)">موضوع، مقاله یا نویسنده‌ای که به دنبالش هستید را جست‌وجو کنید.</p><div className="mt-7 flex flex-wrap justify-center gap-2" aria-label="دسته‌بندی‌های پیشنهادی">{categories.slice(0, 6).map((category) => <Link key={category.id} href={`/categories/${category.slug}`} className="rounded-full border border-(--border-strong) bg-white px-4 py-2 text-[12px] font-bold text-(--text-secondary) hover:border-(--border-strong) hover:text-(--brand-teal)">{category.name}</Link>)}</div></section>;
}

export function NoSearchResults({ query, categories }: { query: string; categories: PublicCategory[] }) {
  return <section className="rounded-(--radius-lg) border border-(--border-strong) bg-white px-5 py-14 text-center"><SearchX className="mx-auto text-(--text-muted)" size={36}/><h2 className="mt-4 text-lg font-black text-(--text-strong)">نتیجه‌ای پیدا نشد</h2><p className="mt-2 text-[13px] leading-6 text-(--text-muted)">برای «{query}» نتیجه‌ای پیدا نکردیم. عبارت کوتاه‌تر یا دیگری را امتحان کنید.</p><div className="mt-6 flex flex-wrap justify-center gap-2">{categories.slice(0, 4).map((category) => <Link key={category.id} href={`/categories/${category.slug}`} className="rounded-full border border-(--border-strong) px-3 py-2 text-[12px] font-bold text-(--text-secondary) hover:border-(--border-strong) hover:text-(--brand-teal)">{category.name}</Link>)}</div></section>;
}

export function SearchContentSkeleton({ hasQuery }: { hasQuery: boolean }) {
  if (!hasQuery) return <><section className="mx-auto max-w-4xl px-4 py-12 text-center md:px-7 md:py-16"><Skeleton className="mx-auto h-6 w-48 rounded"/><Skeleton className="mx-auto mt-4 h-3.5 w-full max-w-xl rounded"/><Skeleton className="mx-auto mt-2 h-3.5 w-3/4 max-w-md rounded"/><div className="mt-7 flex flex-wrap justify-center gap-2">{Array.from({ length: 6 }, (_, index) => <Skeleton key={index} className="h-10 w-24 rounded-full"/>)}</div></section><NewsletterSkeleton/></>;

  return <><section className="mx-auto max-w-360 px-4 pt-9 md:px-7"><Skeleton className="h-6 w-72 max-w-[80vw] rounded"/><Skeleton className="mt-2 h-3 w-44 rounded"/></section><div className="mx-auto grid max-w-360 gap-6 px-4 py-10 md:px-7 md:py-14 xl:grid-cols-[minmax(0,1fr)_300px]"><section className="overflow-hidden rounded-(--radius-lg) border border-(--border-strong) bg-white"><div className="flex flex-col gap-4 border-b border-(--border-subtle) px-5 py-5 sm:flex-row sm:items-end sm:justify-between md:px-6"><div className="space-y-2"><Skeleton className="h-3 w-20 rounded"/><Skeleton className="h-6 w-36 rounded"/><Skeleton className="h-3 w-24 rounded"/></div><Skeleton className="h-10 w-36 rounded-(--radius-sm)"/></div><div className="space-y-7 p-5 md:p-6">{Array.from({ length: 4 }, (_, index) => <ArticleCardSkeleton key={index} variant="horizontal"/>)}</div><PaginationSkeleton/></section><aside className="space-y-5"><section className="rounded-(--radius-lg) border border-(--border-strong) bg-white p-5"><Skeleton className="h-5 w-32 rounded"/><div className="mt-4 space-y-3">{Array.from({ length: 3 }, (_, index) => <div key={index} className="flex items-center gap-3"><Skeleton className="size-10 shrink-0 rounded-full"/><div className="flex-1 space-y-2"><Skeleton className="h-3 w-3/4 rounded"/><Skeleton className="h-2.5 w-1/2 rounded"/></div></div>)}</div></section><section className="rounded-(--radius-lg) border border-(--border-strong) bg-white p-5"><Skeleton className="h-5 w-36 rounded"/><div className="mt-4 flex flex-wrap gap-2">{Array.from({ length: 5 }, (_, index) => <Skeleton key={index} className="h-10 w-24 rounded-full"/>)}</div></section></aside></div><NewsletterSkeleton/></>;
}

export function SearchPageSkeleton({ hasQuery = true }: { hasQuery?: boolean }) {
  return <LoadingStatus label="در حال جست‌وجو"><main id="main-content"><section className="border-b border-(--border-strong) bg-white"><div className="mx-auto max-w-360 px-4 py-10 text-center md:px-7 md:py-14"><Skeleton className="mx-auto h-3 w-32 rounded"/><Skeleton className="mx-auto mt-3 h-10 w-48 rounded"/><Skeleton className="mx-auto mt-4 h-3.5 w-80 max-w-full rounded"/><div className="mx-auto mt-7 flex w-full max-w-3xl flex-col gap-2 sm:flex-row"><Skeleton className="h-14 min-w-0 flex-1 rounded-(--radius)"/><Skeleton className="h-14 w-full rounded-(--radius) sm:w-28"/></div></div></section><SearchContentSkeleton hasQuery={hasQuery}/></main></LoadingStatus>;
}
