import { ArrowLeft, Compass, UserRound } from "lucide-react";
import Link from "next/link";
import type { PublicAuthor, PublicCategory } from "@/lib/public-data";

export function SearchDiscovery({ authors, categories }: { authors: PublicAuthor[]; categories: PublicCategory[] }) {
  if (!authors.length && !categories.length) return null;
  return <aside className="space-y-5" aria-label="نتایج مرتبط">{authors.length > 0 && <section className="rounded-(--radius-lg) border border-(--border-strong) bg-white p-5" aria-labelledby="matching-authors-title"><div className="flex items-center gap-2"><UserRound size={15} className="text-(--brand-teal)"/><h2 id="matching-authors-title" className="text-sm font-black text-(--text-strong)">نویسندگان مرتبط</h2></div><div className="mt-4 space-y-2">{authors.map((author) => <Link key={author.id} href={`/authors/${author.username}`} className="group flex items-center gap-3 rounded-(--radius-sm) border border-(--border-subtle) p-3 hover:border-(--border-strong) hover:bg-(--surface-subtle)"><span className={`grid size-10 shrink-0 place-items-center rounded-full text-[12px] font-black ${author.avatarColor}`}>{author.initials}</span><span className="min-w-0 flex-1"><strong className="block truncate text-[13px] text-(--text-strong)">{author.name}</strong><small className="mt-1 block truncate text-[14px] text-(--text-muted)">{author.roleLabel}</small></span><ArrowLeft size={13} className="text-(--text-muted) transition-transform group-hover:-translate-x-1"/></Link>)}</div></section>}
    {categories.length > 0 && <section className="rounded-(--radius-lg) border border-(--border-strong) bg-white p-5" aria-labelledby="matching-categories-title"><div className="flex items-center gap-2"><Compass size={15} className="text-(--brand-teal)"/><h2 id="matching-categories-title" className="text-sm font-black text-(--text-strong)">دسته‌بندی‌های مرتبط</h2></div><div className="mt-4 space-y-2">{categories.map((category) => <Link key={category.id} href={`/categories/${category.slug}`} className="group flex items-center justify-between rounded-(--radius-sm) border border-(--border-subtle) px-3 py-3 hover:border-(--border-strong) hover:bg-(--surface-subtle)"><span className="flex min-w-0 items-center gap-2 text-[13px] font-bold text-(--text-secondary)"><span className="size-2 shrink-0 rounded-full" style={{ backgroundColor: category.color }}/><span className="truncate">{category.name}</span></span><ArrowLeft size={13} className="shrink-0 text-(--text-muted) transition-transform group-hover:-translate-x-1"/></Link>)}</div></section>}
  </aside>;
}
