import { apiError, apiSuccess, handleApiError } from "@/lib/api-response";
import { assertJsonMutation, enforceApiRateLimit } from "@/lib/api-security";
import { requireRole } from "@/lib/auth";
import { isSupabaseConfigured } from "@/lib/env";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { assertMutationRequest } from "@/lib/request-security";
import { profilePatchSchema, uuidSchema } from "@/lib/validation";
type Context = { params: Promise<{ id: string }> };
export async function PATCH(request: Request, { params }: Context) { if (!isSupabaseConfigured) return apiError("اتصال Supabase تنظیم نشده است.",503); try { assertJsonMutation(request,16*1024);const access=await requireRole(["admin"]);if(!access.ok)return apiError(access.error,access.status);await enforceApiRateLimit(request,"profile-write",30,600,access.profile.id);const input=profilePatchSchema.parse(await request.json());const id=uuidSchema.parse((await params).id);if(input.email!==undefined){if(!process.env.SUPABASE_SERVICE_ROLE_KEY)return apiError("کلید server-only مدیریت کاربران تنظیم نشده است.",503);const{error:authError}=await createSupabaseAdminClient().auth.admin.updateUserById(id,{email:input.email});if(authError)throw authError;}const row={...(input.displayName!==undefined?{display_name:input.displayName}:{}),...(input.username!==undefined?{username:input.username}:{}),...(input.avatarUrl!==undefined?{avatar_url:input.avatarUrl}:{}),...(input.bio!==undefined?{bio:input.bio}:{}),...(input.role!==undefined?{role:input.role}:{}),...(input.isActive!==undefined?{is_active:input.isActive}:{})};const{data,error}=await(await createSupabaseServerClient()).from("profiles").update(row).eq("id",id).select("*").single();if(error)throw error;return apiSuccess(data);}catch(error){return handleApiError(error);} }
export async function DELETE(request: Request, { params }: Context) { if (!isSupabaseConfigured)return apiError("اتصال Supabase تنظیم نشده است.",503);if(!process.env.SUPABASE_SERVICE_ROLE_KEY)return apiError("کلید server-only مدیریت کاربران تنظیم نشده است.",503);try{assertMutationRequest(request);const access=await requireRole(["admin"]);if(!access.ok)return apiError(access.error,access.status);await enforceApiRateLimit(request,"profile-delete",10,3600,access.profile.id);const id=uuidSchema.parse((await params).id);if(id===access.profile.id)return apiError("نمی‌توانید حساب فعال خودتان را حذف کنید.",422);const{error}=await createSupabaseAdminClient().auth.admin.deleteUser(id);if(error)throw error;return apiSuccess({id});}catch(error){return handleApiError(error);} }
