import { bigint, boolean, integer, jsonb, pgEnum, pgTable, primaryKey, text, timestamp, uniqueIndex, uuid, type AnyPgColumn } from "drizzle-orm/pg-core";

export const appRole = pgEnum("app_role", ["admin", "editor", "author"]);
export const contentStatus = pgEnum("content_status", ["draft", "review", "published", "scheduled", "archived"]);
export const commentStatus = pgEnum("comment_status", ["pending", "approved", "rejected", "spam"]);

export const profiles = pgTable("profiles", {
  id: uuid("id").primaryKey(), displayName: text("display_name").notNull(), username: text("username").notNull(), avatarUrl: text("avatar_url"), bio: text("bio").notNull().default(""), role: appRole("role").notNull().default("author"), isActive: boolean("is_active").notNull().default(true), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex("profiles_username_key").on(table.username)]);

export const categories = pgTable("categories", {
  id: uuid("id").defaultRandom().primaryKey(), name: text("name").notNull(), slug: text("slug").notNull(), description: text("description").notNull().default(""), icon: text("icon").notNull().default("Folder"), color: text("color").notNull().default("#176f66"), parentId: uuid("parent_id").references((): AnyPgColumn => categories.id, { onDelete: "set null" }), coverImage: text("cover_image"), seo: jsonb("seo").notNull().default({}), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex("categories_slug_key").on(table.slug)]);

export const tags = pgTable("tags", { id: uuid("id").defaultRandom().primaryKey(), name: text("name").notNull(), slug: text("slug").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("tags_slug_key").on(table.slug)]);

export const articles = pgTable("articles", {
  id: uuid("id").defaultRandom().primaryKey(), title: text("title").notNull(), slug: text("slug").notNull(), excerpt: text("excerpt").notNull().default(""), content: text("content").notNull().default(""), coverUrl: text("cover_url"), authorId: uuid("author_id").notNull().references(() => profiles.id, { onDelete: "restrict" }), categoryId: uuid("category_id").references(() => categories.id, { onDelete: "set null" }), status: contentStatus("status").notNull().default("draft"), readingTime: integer("reading_time").notNull().default(1), views: bigint("views", { mode: "number" }).notNull().default(0), publishedAt: timestamp("published_at", { withTimezone: true }), scheduledAt: timestamp("scheduled_at", { withTimezone: true }), seo: jsonb("seo").notNull().default({}), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex("articles_slug_key").on(table.slug)]);

export const articleTags = pgTable("article_tags", { articleId: uuid("article_id").notNull().references(() => articles.id, { onDelete: "cascade" }), tagId: uuid("tag_id").notNull().references(() => tags.id, { onDelete: "cascade" }) }, (table) => [primaryKey({ columns: [table.articleId, table.tagId] })]);

export const comments = pgTable("comments", { id: uuid("id").defaultRandom().primaryKey(), articleId: uuid("article_id").notNull().references(() => articles.id, { onDelete: "cascade" }), parentId: uuid("parent_id"), userId: uuid("user_id").references(() => profiles.id, { onDelete: "set null" }), name: text("name").notNull(), email: text("email").notNull(), content: text("content").notNull(), status: commentStatus("status").notNull().default("pending"), likes: integer("likes").notNull().default(0), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() });

export const media = pgTable("media", { id: uuid("id").defaultRandom().primaryKey(), ownerId: uuid("owner_id").notNull().references(() => profiles.id, { onDelete: "restrict" }), name: text("name").notNull(), path: text("path").notNull(), url: text("url").notNull(), mimeType: text("mime_type").notNull(), size: bigint("size", { mode: "number" }).notNull(), width: integer("width"), height: integer("height"), altText: text("alt_text").notNull().default(""), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("media_path_key").on(table.path)]);

export const siteSettings = pgTable("site_settings", { id: uuid("id").defaultRandom().primaryKey(), key: text("key").notNull(), value: jsonb("value").notNull().default({}), updatedBy: uuid("updated_by").references(() => profiles.id, { onDelete: "set null" }), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("site_settings_key_key").on(table.key)]);
export const newsletterSubscribers = pgTable("newsletter_subscribers", { id: uuid("id").defaultRandom().primaryKey(), email: text("email").notNull(), isActive: boolean("is_active").notNull().default(true), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("newsletter_email_key").on(table.email)]);
export const articleRevisions = pgTable("article_revisions", { id: uuid("id").defaultRandom().primaryKey(), articleId: uuid("article_id").notNull().references(() => articles.id, { onDelete: "cascade" }), editorId: uuid("editor_id").notNull().references(() => profiles.id, { onDelete: "restrict" }), snapshot: jsonb("snapshot").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const rateLimits = pgTable("rate_limits", { key: text("key").primaryKey(), hits: integer("hits").notNull().default(1), windowStarted: timestamp("window_started", { withTimezone: true }).notNull().defaultNow() });
