import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { ArticleAuthorCard } from "@/components/public/article/article-author-card";
import { ArticleComments } from "@/components/public/article/article-comments";
import { ArticleContent } from "@/components/public/article/article-content";
import { ArticleFeaturedImage, ArticleHeader } from "@/components/public/article/article-header";
import { ArticleTableOfContents } from "@/components/public/article/article-toc";
import { ArticleShare, ReadingProgress } from "@/components/public/article/article-tools";
import { RelatedArticles } from "@/components/public/article/related-articles";
import { NewsletterSection } from "@/components/public/newsletter-section";
import { PublicFooter } from "@/components/public/public-footer";
import { PublicHeader } from "@/components/public/public-header";
import { getArticleBySlug, getPublishedArticleSlugs, getRelatedArticles } from "@/lib/public-article-service";

type Props = { params: Promise<{ slug: string }> };
export const dynamicParams = false;
export function generateStaticParams() { return getPublishedArticleSlugs().map((slug) => ({ slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const article = await getArticleBySlug(slug); if (!article) return { title: "مقاله پیدا نشد", robots: { index: false, follow: false } }; const url = `https://technama.ir/articles/${article.slug}`; const image = `https://technama.ir${article.image}`; return { title: `${article.title}`, description: article.excerpt, alternates: { canonical: url }, authors: [{ name: article.authorDetails.name, url: `https://technama.ir/authors/${article.authorDetails.username}` }], robots: { index: true, follow: true }, openGraph: { type: "article", locale: "fa_IR", url, siteName: "تک‌نما", title: article.title, description: article.excerpt, publishedTime: article.publishedAt || article.createdAt, modifiedTime: article.updatedAt, authors: [article.authorDetails.name], images: [{ url: image, width: 1200, height: 630, alt: article.title }] }, twitter: { card: "summary_large_image", title: article.title, description: article.excerpt, images: [image] } }; }
export default async function ArticlePage({ params }: Props) { const { slug } = await params; const article = await getArticleBySlug(slug); if (!article) notFound(); const related = await getRelatedArticles(article); const structuredData = { "@context": "https://schema.org", "@type": "Article", headline: article.title, description: article.excerpt, image: [`https://technama.ir${article.image}`], datePublished: article.publishedAt || article.createdAt, dateModified: article.updatedAt, author: { "@type": "Person", name: article.authorDetails.name, url: `https://technama.ir/authors/${article.authorDetails.username}` }, publisher: { "@type": "Organization", name: "تک‌نما", logo: { "@type": "ImageObject", url: "https://technama.ir/media/design-system.svg" } }, mainEntityOfPage: `https://technama.ir/articles/${article.slug}` }; return <div className="public-site min-h-screen"><PublicHeader/><ReadingProgress/><main id="main-content" tabIndex={-1}><ArticleHeader article={article}/><ArticleFeaturedImage article={article}/><div className="mx-auto grid max-w-6xl gap-8 px-4 py-10 md:px-7 md:py-14 xl:grid-cols-[160px_minmax(0,720px)_110px]"><ArticleTableOfContents content={article.content}/><div className="min-w-0"><ArticleContent article={article}/><ArticleAuthorCard author={article.authorDetails}/></div><ArticleShare title={article.title}/></div><ArticleComments comments={article.approvedComments}/><RelatedArticles articles={related}/><div className="pt-14"><NewsletterSection/></div></main><PublicFooter/><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, "\\u003c") }}/></div>; }
