"use client";
import { CalendarDays } from "lucide-react";
import { useState } from "react";
import { analyticsRangeLabels, type AnalyticsRange } from "@/lib/analytics-data";

export function AnalyticsHeader({ range, onRangeChange }: { range: AnalyticsRange; onRangeChange: (range: AnalyticsRange) => void }) {
  const [customOpen, setCustomOpen] = useState(false); const [from, setFrom] = useState("2026-08-01"); const [to, setTo] = useState("2026-09-08");
  return <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="mb-2 text-[13px] font-bold text-(--accent)">بینش تحریریه</p><h2 className="text-xl font-bold tracking-[-.03em] text-(--text-strong) sm:text-2xl">آمار و تحلیل</h2><p className="mt-2 text-xs text-(--muted)">بررسی عملکرد محتوا، مخاطبان و روند رشد مجله</p></div><div className="relative"><label className="flex h-11 min-w-48 items-center gap-2 rounded-(--radius-sm) border border-(--border) bg-white px-3 text-(--text-secondary)"><CalendarDays size={16}/><span className="sr-only">انتخاب بازه زمانی</span><select value={range} onChange={(event) => { const value = event.target.value as AnalyticsRange; if (value === "custom") setCustomOpen(true); else { setCustomOpen(false); onRangeChange(value); } }} className="h-full flex-1 bg-transparent text-[13px] font-bold outline-none">{Object.entries(analyticsRangeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>{customOpen && <div className="absolute left-0 top-13 z-30 w-72 rounded-(--radius) border border-(--border) bg-white p-4 shadow-[0_14px_38px_rgba(23,38,48,.14)]"><p className="text-[13px] font-bold text-(--text-secondary)">انتخاب بازه دلخواه</p><div className="mt-3 grid grid-cols-2 gap-2"><label className="text-[14px] text-(--text-muted)">از<input type="date" value={from} onChange={(event) => setFrom(event.target.value)} className="mt-1 h-10 w-full rounded-(--radius-sm) border border-(--border) px-2 text-[12px] outline-none"/></label><label className="text-[14px] text-(--text-muted)">تا<input type="date" value={to} onChange={(event) => setTo(event.target.value)} className="mt-1 h-10 w-full rounded-(--radius-sm) border border-(--border) px-2 text-[12px] outline-none"/></label></div><button type="button" disabled={!from || !to || from > to} onClick={() => { onRangeChange("custom"); setCustomOpen(false); }} className="mt-3 h-10 w-full rounded-(--radius-sm) bg-(--brand-navy) text-[12px] font-bold text-white disabled:opacity-45">اعمال بازه</button></div>}</div></div>;
}

