"use client";
import { useState } from "react";
import type { AnalyticsPoint, ChartMetric } from "@/lib/analytics-data";
const metricLabels: Record<ChartMetric, string> = { views: "بازدید", visitors: "بازدیدکنندگان", engagement: "تعامل" };
export function TrafficChart({ points, rangeLabel }: { points: AnalyticsPoint[]; rangeLabel: string }) {
  const [metric, setMetric] = useState<ChartMetric>("views");
  const values = points.map((point) => point[metric]); const max = Math.max(...values, 1); const width = 720; const height = 230; const padX = 26; const padY = 22;
  const coords = values.map((value, index) => ({ x: padX + index * ((width - padX * 2) / Math.max(values.length - 1, 1)), y: height - padY - (value / max) * (height - padY * 2), value, label: points[index].label }));
  const path = coords.map((point, index) => `${index ? "L" : "M"}${point.x},${point.y}`).join(" ");
  const average = values.reduce((sum, value) => sum + value, 0) / Math.max(values.length, 1);
  return <section className="rounded-(--radius) border border-(--border) bg-white p-4 sm:p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><h3 className="text-xs font-bold text-(--text-strong)">روند بازدید</h3><p className="mt-1 text-[12px] text-(--text-muted)">مقایسه پیوسته عملکرد در {rangeLabel}</p></div><div role="group" aria-label="انتخاب معیار نمودار" className="flex rounded-(--radius-sm) bg-(--surface-muted) p-1">{Object.entries(metricLabels).map(([value, label]) => <button key={value} type="button" onClick={() => setMetric(value as ChartMetric)} aria-pressed={metric === value} className={`h-10 rounded-(--radius-sm) px-3 text-[12px] font-bold ${metric === value ? "bg-white text-(--brand-teal) shadow-sm" : "text-(--text-muted)"}`}>{label}</button>)}</div></div>{points.length ? <><div className="mt-5 overflow-hidden" role="img" aria-label={`نمودار ${metricLabels[metric]} با ${points.length.toLocaleString("fa-IR")} نقطه زمانی`}><svg viewBox={`0 0 ${width} ${height}`} className="h-58 w-full" preserveAspectRatio="none"><g stroke="#e8ecee" strokeWidth="1">{[0, .25, .5, .75, 1].map((part) => <line key={part} x1={padX} x2={width - padX} y1={padY + part * (height - padY * 2)} y2={padY + part * (height - padY * 2)}/>)}</g><path d={`${path} L${coords.at(-1)?.x},${height - padY} L${coords[0]?.x},${height - padY} Z`} fill="#168579" opacity=".08"/><path d={path} fill="none" stroke="#167c72" strokeWidth="3" strokeLinejoin="round" strokeLinecap="round" vectorEffect="non-scaling-stroke"/>{coords.map((point) => <circle key={`${point.label}-${point.x}`} cx={point.x} cy={point.y} r="4" fill="#fff" stroke="#167c72" strokeWidth="2" tabIndex={0} aria-label={`${point.label}: ${formatValue(point.value, metric)}`}><title>{point.label}: {formatValue(point.value, metric)}</title></circle>)}</svg></div><div className="grid grid-cols-6 gap-1 text-center text-[14px] text-(--text-muted)">{points.filter((_, index) => index % 2 === 0).map((point) => <span key={point.label} className="truncate">{point.label}</span>)}</div><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 border-t border-(--border-subtle) pt-4 text-[14px] text-(--text-muted)"><span>کمینه: <strong className="text-(--text-secondary)">{formatValue(Math.min(...values), metric)}</strong></span><span>بیشینه: <strong className="text-(--text-secondary)">{formatValue(max, metric)}</strong></span><span>میانگین: <strong className="text-(--text-secondary)">{formatValue(average, metric)}</strong></span></div></> : <p className="grid h-64 place-items-center text-[13px] text-(--text-muted)">داده‌ای برای نمایش وجود ندارد</p>}</section>;
}
function formatValue(value: number, metric: ChartMetric) { return metric === "engagement" ? `${value.toLocaleString("fa-IR", { maximumFractionDigits: 1 })}٪` : Math.round(value).toLocaleString("fa-IR"); }
