import { Search, SlidersHorizontal, X } from "lucide-react";

export type MediaTypeFilter = "all" | "image" | "document";
export type MediaSort = "newest" | "oldest" | "name" | "size";
const selectClass = "h-10 min-w-0 rounded-(--radius-sm) border border-(--border) bg-white px-3 text-[14px] font-bold text-(--text-secondary) outline-none transition-colors hover:border-(--border-strong) focus:border-(--focus-border)";

export function MediaToolbar({ query, type, sort, resultCount, onQueryChange, onTypeChange, onSortChange, onReset }: { query: string; type: MediaTypeFilter; sort: MediaSort; resultCount: number; onQueryChange: (value: string) => void; onTypeChange: (value: MediaTypeFilter) => void; onSortChange: (value: MediaSort) => void; onReset: () => void }) {
  const hasFilters = query || type !== "all";
  return <section className="rounded-(--radius) border border-(--border) bg-white p-3 sm:p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-center"><label className="flex h-10 flex-1 items-center gap-2 rounded-(--radius-sm) border border-(--border) bg-(--surface-subtle) px-3 text-(--muted) transition-colors focus-within:border-(--border-strong) focus-within:bg-white"><Search size={17}/><span className="sr-only">جستجوی فایل</span><input value={query} onChange={(event) => onQueryChange(event.target.value)} className="h-full w-full bg-transparent text-xs text-(--text-strong) outline-none placeholder:text-(--text-faint)" placeholder="جستجوی فایل..."/>{query && <button type="button" onClick={() => onQueryChange("")} aria-label="پاک‌کردن جستجو" className="grid size-7 place-items-center rounded-md hover:bg-(--surface-muted)"><X size={14}/></button>}</label><div className="grid grid-cols-2 gap-2 sm:flex"><label className="sr-only" htmlFor="media-type">نوع فایل</label><select id="media-type" value={type} onChange={(event) => onTypeChange(event.target.value as MediaTypeFilter)} className={selectClass}><option value="all">همه فایل‌ها</option><option value="image">تصاویر</option><option value="document">اسناد</option></select><label className="sr-only" htmlFor="media-sort">مرتب‌سازی</label><select id="media-sort" value={sort} onChange={(event) => onSortChange(event.target.value as MediaSort)} className={selectClass}><option value="newest">جدیدترین</option><option value="oldest">قدیمی‌ترین</option><option value="name">نام فایل</option><option value="size">حجم فایل</option></select></div></div><div className="mt-3 flex min-h-7 items-center justify-between gap-3 border-t border-(--border-subtle) pt-3 text-[13px] text-(--text-muted)"><span className="flex items-center gap-1.5"><SlidersHorizontal size={13}/> {new Intl.NumberFormat("fa-IR").format(resultCount)} نتیجه</span>{hasFilters && <button type="button" onClick={onReset} className="font-bold text-(--accent) hover:text-(--brand-teal)">پاک‌کردن فیلترها</button>}</div></section>;
}

