"use client";

import Image from "next/image";
import { Copy, Eye, FileText, MoreHorizontal, Pencil, Trash2 } from "lucide-react";
import { useState } from "react";
import type { MediaAsset } from "@/lib/media-data";
import { fileExtension, formatBytes, formatMediaDate } from "./media-utils";

export function MediaCard({ asset, selected, onSelect, onOpen, onRename, onCopy, onDelete }: { asset: MediaAsset; selected: boolean; onSelect: () => void; onOpen: () => void; onRename: () => void; onCopy: () => void; onDelete: () => void }) {
  const [menuOpen, setMenuOpen] = useState(false);
  return <article className={`group relative overflow-hidden rounded-(--radius) border bg-white transition-all hover:-translate-y-0.5 hover:shadow-[0_10px_28px_rgba(23,45,58,.09)] ${selected ? "border-(--brand-teal) ring-2 ring-(--brand-teal)/15" : "border-(--border) hover:border-(--border-strong)"}`}><button type="button" onClick={onOpen} className="relative block aspect-4/3 w-full overflow-hidden bg-(--surface-muted) text-right" aria-label={`پیش‌نمایش ${asset.name}`}>{asset.type === "image" ? <Image src={asset.thumbnailUrl || asset.url} alt={asset.altText || asset.name} fill sizes="(max-width: 640px) 50vw, (max-width: 1280px) 33vw, 20vw" className="object-cover transition-transform duration-300 group-hover:scale-[1.025]" unoptimized={asset.url.startsWith("blob:")}/> : <span className="grid h-full place-items-center bg-(--surface-muted) text-(--text-secondary)"><span className="text-center"><FileText className="mx-auto" size={38} strokeWidth={1.4}/><small className="mt-2 block text-[13px] font-bold">PDF</small></span></span>}<span className="absolute inset-0 grid place-items-center bg-(--brand-navy)/0 text-white opacity-0 transition-all group-hover:bg-(--brand-navy)/25 group-hover:opacity-100"><Eye size={23}/></span></button><label className="absolute right-2.5 top-2.5 grid size-10 cursor-pointer place-items-center rounded-lg border border-white/70 bg-white/90 shadow-sm"><span className="sr-only">انتخاب {asset.name}</span><input type="checkbox" checked={selected} onChange={onSelect} className="size-4 accent-[#14796f]"/></label><div className="p-3"><div className="flex items-start gap-2"><div className="min-w-0 flex-1"><h3 className="truncate text-[14px] font-bold text-(--text-strong)" dir="ltr" title={asset.name}>{asset.name}</h3><p className="mt-1 text-[12px] text-(--text-muted)">{fileExtension(asset.name)} · {formatBytes(asset.size)}</p><p className="mt-1.5 text-[12px] text-(--text-faint)">{formatMediaDate(asset.createdAt)}</p></div><div className="relative"><button type="button" onClick={() => setMenuOpen((value) => !value)} aria-label={`عملیات ${asset.name}`} aria-expanded={menuOpen} className="grid size-10 place-items-center rounded-lg text-(--text-muted) hover:bg-(--surface-muted)"><MoreHorizontal size={17}/></button>{menuOpen && <div className="absolute bottom-9 left-0 z-20 w-31 rounded-(--radius-sm) border border-(--border) bg-white p-1 shadow-[0_12px_32px_rgba(16,24,32,.16)]"><Action icon={Eye} label="مشاهده" onClick={onOpen}/><Action icon={Pencil} label="تغییر نام" onClick={onRename}/><Action icon={Copy} label="کپی لینک" onClick={onCopy}/><Action icon={Trash2} label="حذف" danger onClick={onDelete}/></div>}</div></div></div></article>;
}

function Action({ icon: Icon, label, onClick, danger = false }: { icon: typeof Eye; label: string; onClick: () => void; danger?: boolean }) { return <button type="button" onClick={onClick} className={`flex h-10 w-full items-center gap-2 rounded-md px-2 text-right text-[12px] font-bold hover:bg-(--surface-muted) ${danger ? "text-(--danger)" : "text-(--text-secondary)"}`}><Icon size={13}/>{label}</button>; }
