import { ArticleCardSkeleton } from "@/components/skeletons/article-card-skeleton";
import { NewsletterSkeleton, PaginationSkeleton, SidebarListSkeleton } from "@/components/skeletons/public-shared-skeletons";
import { LoadingStatus, Skeleton } from "@/components/ui/skeleton";

export function AuthorPageSkeleton() {
  return <LoadingStatus label="در حال بارگذاری نویسنده">
    <main id="main-content">
      <section className="border-b border-(--border-strong) bg-white"><div className="mx-auto max-w-360 px-4 py-8 md:px-7 md:py-12"><div className="flex gap-2"><Skeleton className="h-3 w-16 rounded"/><Skeleton className="h-3 w-20 rounded"/><Skeleton className="h-3 w-24 rounded"/></div><div className="mt-8 grid items-center gap-7 md:grid-cols-[auto_minmax(0,1fr)] md:gap-9"><Skeleton className="size-28 rounded-full sm:size-36"/><div className="min-w-0"><Skeleton className="h-3 w-28 rounded"/><Skeleton className="mt-4 h-10 w-64 max-w-[75vw] rounded"/><div className="mt-3 flex gap-3"><Skeleton className="h-3 w-24 rounded"/><Skeleton className="h-3 w-28 rounded"/></div><Skeleton className="mt-5 h-4 w-full max-w-3xl rounded"/><Skeleton className="mt-3 h-4 w-4/5 max-w-2xl rounded"/><div className="mt-5 flex gap-2">{Array.from({ length: 4 }, (_, index) => <Skeleton key={index} className="size-10 rounded-(--radius-sm)"/>)}</div></div></div><div className="mt-9 grid grid-cols-2 overflow-hidden rounded-(--radius) border border-(--border-strong) bg-(--surface-subtle) sm:grid-cols-3">{Array.from({ length: 3 }, (_, index) => <div key={index} className={`p-4 sm:p-5 ${index === 2 ? "col-span-2 border-t border-(--border-strong) sm:col-span-1 sm:border-t-0" : index === 0 ? "border-l border-(--border-strong)" : "sm:border-l sm:border-(--border-strong)"}`}><Skeleton className="h-3 w-28 rounded"/><Skeleton className="mt-3 h-6 w-20 rounded"/></div>)}</div></div></section>
      <section className="mx-auto max-w-360 px-4 pt-10 md:px-7 md:pt-14"><div className="mb-5 flex items-end gap-3"><div className="space-y-2"><Skeleton className="h-3 w-24 rounded"/><Skeleton className="h-6 w-44 rounded"/></div><Skeleton className="h-px flex-1"/></div><ArticleCardSkeleton variant="featured"/></section>
      <div className="mx-auto grid max-w-360 gap-6 px-4 py-10 md:px-7 md:py-14 xl:grid-cols-[minmax(0,1fr)_300px]"><section className="overflow-hidden rounded-(--radius-lg) border border-(--border-strong) bg-white"><div className="flex flex-col gap-4 border-b border-(--border-subtle) px-5 py-5 sm:flex-row sm:items-end sm:justify-between md:px-6"><div className="space-y-2"><Skeleton className="h-3 w-24 rounded"/><Skeleton className="h-6 w-44 rounded"/></div><Skeleton className="h-10 w-36 rounded-(--radius-sm)"/></div><div className="grid gap-x-5 gap-y-9 p-5 sm:grid-cols-2 md:p-6">{Array.from({ length: 4 }, (_, index) => <ArticleCardSkeleton key={index}/>)}</div><PaginationSkeleton/></section><SidebarListSkeleton rows={3}/></div>
      <NewsletterSkeleton/>
    </main>
  </LoadingStatus>;
}
