import { ArrowLeft, Clock3 } from "lucide-react";
import Link from "next/link";
import type { PublicAuthorDetail } from "@/lib/public-author-service";
import type { PublicArticle } from "@/lib/public-data";

export function AuthorDiscovery({ authors, popular }: { authors: PublicAuthorDetail[]; popular: PublicArticle[] }) {
  return <aside className="space-y-5" aria-label="پیشنهادهای مرتبط"><section className="rounded-(--radius-lg) border border-(--border-strong) bg-white p-5" aria-labelledby="author-popular-title"><p className="text-[12px] font-bold text-(--brand-teal)">منتخب خوانندگان</p><h2 id="author-popular-title" className="mt-1 text-base font-black text-(--text-strong)">پربازدیدترین نوشته‌ها</h2><ol className="mt-5 space-y-4">{popular.map((article, index) => <li key={article.id} className="flex gap-3 border-b border-(--border-subtle) pb-4 last:border-0 last:pb-0"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-(--surface-muted) text-[13px] font-black text-(--brand-teal)">{(index + 1).toLocaleString("fa-IR")}</span><div><Link href={`/articles/${article.slug}`} className="line-clamp-2 text-[14px] font-bold leading-6 text-(--text-strong) hover:text-(--brand-teal)">{article.title}</Link><span className="mt-1.5 inline-flex items-center gap-1 text-[14px] text-(--text-muted)"><Clock3 size={10}/>{article.readingTime.toLocaleString("fa-IR")} دقیقه مطالعه</span></div></li>)}</ol></section>
    <section className="rounded-(--radius-lg) border border-(--border-strong) bg-white p-5" aria-labelledby="related-authors-title"><h2 id="related-authors-title" className="text-base font-black text-(--text-strong)">نویسندگان دیگر</h2><div className="mt-4 space-y-2">{authors.map((author) => <Link key={author.id} href={`/authors/${author.username}`} className="group flex items-center gap-3 rounded-(--radius-sm) border border-(--border-subtle) p-3 hover:border-(--border-strong) hover:bg-(--surface-subtle)"><span className={`grid size-10 shrink-0 place-items-center rounded-full text-[12px] font-black ${author.avatarColor}`}>{author.initials}</span><span className="min-w-0 flex-1"><strong className="block truncate text-[13px] text-(--text-strong)">{author.name}</strong><small className="mt-1 block truncate text-[14px] text-(--text-muted)">{author.roleLabel}</small></span><ArrowLeft size={13} className="text-(--text-muted) transition-transform group-hover:-translate-x-1"/></Link>)}</div></section></aside>;
}
