import type { ReactNode } from "react";

export const inputClass = "mt-2 h-11 w-full rounded-(--radius-sm) border border-(--border) bg-white px-3 text-[14px] text-(--text-secondary) outline-none transition-colors placeholder:text-(--text-faint) focus:border-(--focus-border) disabled:bg-(--surface-muted)";
export const textareaClass = "mt-2 w-full resize-none rounded-(--radius-sm) border border-(--border) bg-white p-3 text-[14px] leading-6 text-(--text-secondary) outline-none transition-colors placeholder:text-(--text-faint) focus:border-(--focus-border)";

export function SettingsSection({ id, title, description, children }: { id: string; title: string; description: string; children: ReactNode }) { return <section id={id} className="scroll-mt-24 rounded-(--radius) border border-(--border) bg-white"><header className="border-b border-(--border-subtle) px-4 py-4 sm:px-5"><h3 className="text-xs font-bold text-(--text-strong)">{title}</h3><p className="mt-1.5 text-[12px] leading-5 text-(--text-muted)">{description}</p></header><div className="p-4 sm:p-5">{children}</div></section>; }

export function SettingField({ label, hint, error, children }: { label: string; hint?: string; error?: string; children: ReactNode }) { return <label className="block"><span className="text-[13px] font-bold text-(--text-secondary)">{label}</span>{children}{error ? <span role="alert" className="mt-1.5 block text-[14px] text-(--danger)">{error}</span> : hint ? <span className="mt-1.5 block text-[14px] leading-4 text-(--text-muted)">{hint}</span> : null}</label>; }

export function SettingToggle({ label, description, checked, onChange, disabled = false }: { label: string; description: string; checked: boolean; onChange: (value: boolean) => void; disabled?: boolean }) { return <div className="flex items-start justify-between gap-4 py-3"><div><p className="text-[13px] font-bold text-(--text-secondary)">{label}</p><p className="mt-1 text-[14px] leading-4 text-(--text-muted)">{description}</p></div><button type="button" role="switch" aria-checked={checked} disabled={disabled} onClick={() => onChange(!checked)} className={`relative mt-0.5 h-6 w-11 shrink-0 rounded-full border transition-colors disabled:opacity-45 ${checked ? "border-(--brand-teal) bg-(--brand-teal)" : "border-(--border-strong) bg-(--surface-muted)"}`}><span className={`absolute top-0.5 size-4.5 rounded-full bg-white shadow-sm transition-transform ${checked ? "right-5.5" : "right-0.5"}`}/><span className="sr-only">{checked ? "فعال" : "غیرفعال"}</span></button></div>; }

