"use client";
import Image from "next/image";
import Link from "next/link";
import { Check, Images, X } from "lucide-react";
import { useEffect } from "react";
import { mockMediaAssets } from "@/lib/media-data";

export function SettingsMediaField({ label, value, onSelect, compact = false }: { label: string; value: string; onSelect: (url: string) => void; compact?: boolean }) {
  const dialogId = `picker-${label.replaceAll(" ", "-")}`;
  return <div><p className="text-[13px] font-bold text-(--text-secondary)">{label}</p><div className="mt-2 flex items-center gap-3 rounded-(--radius) border border-(--border) bg-(--surface-subtle) p-3"><div className={`relative shrink-0 overflow-hidden rounded-(--radius-sm) border border-(--border-strong) bg-white ${compact ? "size-12" : "h-18 w-26"}`}><Image src={value} alt={`پیش‌نمایش ${label}`} fill sizes={compact ? "48px" : "104px"} className="object-cover"/></div><div className="min-w-0 flex-1"><p dir="ltr" className="truncate text-left text-[14px] text-(--text-muted)">{value}</p><button type="button" onClick={() => (document.getElementById(dialogId) as HTMLDialogElement)?.showModal()} className="mt-2 h-10 rounded-(--radius-sm) border border-(--border) bg-white px-3 text-[12px] font-bold text-(--text-secondary) hover:bg-(--surface-muted)">انتخاب از رسانه‌ها</button></div></div><MediaPickerDialog id={dialogId} label={label} value={value} onSelect={onSelect}/></div>;
}

function MediaPickerDialog({ id, label, value, onSelect }: { id: string; label: string; value: string; onSelect: (url: string) => void }) {
  useEffect(() => { const dialog = document.getElementById(id) as HTMLDialogElement | null; const close = (event: KeyboardEvent) => { if (event.key === "Escape") dialog?.close(); }; document.addEventListener("keydown", close); return () => document.removeEventListener("keydown", close); }, [id]);
  const images = mockMediaAssets.filter((item) => item.type === "image").slice(0, 12);
  return <dialog id={id} aria-labelledby={`${id}-title`} className="m-auto max-h-[90vh] w-[calc(100%-2rem)] max-w-2xl rounded-(--radius-lg) border border-(--border) bg-white p-0 text-right shadow-[0_24px_70px_rgba(16,24,32,.24)] backdrop:bg-(--brand-navy)/50"><header className="flex h-14 items-center justify-between border-b border-(--border-subtle) px-4"><h3 id={`${id}-title`} className="flex items-center gap-2 text-xs font-bold text-(--text-strong)"><Images size={16}/> انتخاب {label}</h3><button type="button" onClick={() => (document.getElementById(id) as HTMLDialogElement)?.close()} aria-label="بستن انتخاب رسانه" className="grid size-10 place-items-center rounded-lg text-(--text-muted) hover:bg-(--surface-muted)"><X size={17}/></button></header><div className="grid grid-cols-2 gap-3 p-4 sm:grid-cols-3 md:grid-cols-4">{images.map((asset) => <button key={asset.id} type="button" onClick={() => { onSelect(asset.url); (document.getElementById(id) as HTMLDialogElement)?.close(); }} className={`relative aspect-4/3 overflow-hidden rounded-(--radius-sm) border-2 bg-(--surface-muted) ${asset.url === value ? "border-(--brand-teal)" : "border-transparent hover:border-(--border-strong)"}`} aria-label={`انتخاب ${asset.name}`}><Image src={asset.url} alt={asset.altText} fill sizes="(max-width: 640px) 45vw, 150px" className="object-cover"/>{asset.url === value && <span className="absolute left-2 top-2 grid size-6 place-items-center rounded-full bg-(--brand-teal) text-white"><Check size={13}/></span>}</button>)}</div><footer className="flex items-center justify-between border-t border-(--border-subtle) px-4 py-3"><Link href="/admin/media" className="text-[12px] font-bold text-(--brand-teal)">مدیریت کامل رسانه‌ها</Link><button type="button" onClick={() => (document.getElementById(id) as HTMLDialogElement)?.close()} className="h-10 rounded-(--radius-sm) border border-(--border) px-3 text-[12px] font-bold text-(--text-secondary)">انصراف</button></footer></dialog>;
}
