"use client";
import { Check, LoaderCircle, Save } from "lucide-react";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import type { SettingsData, SettingsSectionId } from "@/lib/settings-data";
import { settingsService } from "@/lib/settings-service";
import { SettingsConfirmDialog, UnsavedChangesDialog } from "./settings-dialogs";
import { SettingsNavigation } from "./settings-navigation";
import { SettingsSections } from "./settings-sections";
import { SettingsError, SettingsSkeleton } from "./settings-states";

export function SettingsForm() {
  const router = useRouter(); const [settings, setSettings] = useState<SettingsData | null>(null); const [saved, setSaved] = useState<SettingsData | null>(null); const [active, setActive] = useState<SettingsSectionId>("general"); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState(false); const [saving, setSaving] = useState(false); const [errors, setErrors] = useState<Record<string, string>>({}); const [notice, setNotice] = useState(""); const [confirmAction, setConfirmAction] = useState<"sessions" | "reset" | null>(null); const [pendingHref, setPendingHref] = useState<string | null>(null);
  const dirty = Boolean(settings && saved && JSON.stringify(settings) !== JSON.stringify(saved));
  const load = async () => { setLoading(true); setLoadError(false); try { const data = await settingsService.get(); setSettings(data); setSaved(data); } catch { setLoadError(true); } finally { setLoading(false); } };
  useEffect(() => { let active = true; settingsService.get().then((data) => { if (active) { setSettings(data); setSaved(data); } }).catch(() => { if (active) setLoadError(true); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  useEffect(() => { const beforeUnload = (event: BeforeUnloadEvent) => { if (!dirty) return; event.preventDefault(); event.returnValue = ""; }; window.addEventListener("beforeunload", beforeUnload); return () => window.removeEventListener("beforeunload", beforeUnload); }, [dirty]);
  useEffect(() => { const intercept = (event: MouseEvent) => { if (!dirty) return; const anchor = (event.target as HTMLElement).closest("a"); const href = anchor?.getAttribute("href"); if (!href || href.startsWith("#") || href === "/admin/settings") return; event.preventDefault(); setPendingHref(href); }; document.addEventListener("click", intercept, true); return () => document.removeEventListener("click", intercept, true); }, [dirty]);
  const showNotice = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(""), 2600); };
  const validate = (value: SettingsData) => { const next: Record<string, string> = {}; if (!value.general.magazineName.trim()) next.magazineName = "وارد کردن نام مجله الزامی است."; if (!value.general.description.trim()) next.description = "توضیحات کوتاه مجله را وارد کنید."; if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value.general.contactEmail)) next.contactEmail = "یک ایمیل معتبر وارد کنید."; if (value.content.articlesPerPage < 5 || value.content.articlesPerPage > 50) next.articlesPerPage = "تعداد مقالات باید بین ۵ تا ۵۰ باشد."; if (!value.seo.defaultTitle.trim()) next.defaultTitle = "عنوان پیش‌فرض SEO الزامی است."; if (value.seo.metaDescription.length > 160) next.metaDescription = "توضیحات متا نباید بیشتر از ۱۶۰ نویسه باشد."; try { new URL(value.seo.siteUrl); } catch { next.siteUrl = "یک آدرس معتبر مانند https://example.com وارد کنید."; } return next; };
  const save = async () => { if (!settings) return; const nextErrors = validate(settings); setErrors(nextErrors); if (Object.keys(nextErrors).length) { showNotice("لطفاً خطاهای فرم را برطرف کنید."); return; } setSaving(true); try { const result = await settingsService.save(settings); setSaved(result); setSettings(result); showNotice("تنظیمات با موفقیت ذخیره شد."); } catch { showNotice("ذخیره تنظیمات با مشکل مواجه شد."); } finally { setSaving(false); } };
  const selectSection = (id: SettingsSectionId) => { setActive(id); document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }); };
  if (loading) return <SettingsSkeleton/>; if (loadError || !settings) return <SettingsError onRetry={load}/>;
  const confirmDanger = async () => { if (confirmAction === "sessions") { await settingsService.signOutOtherSessions(); const keepCurrentSession = (current: SettingsData | null) => current ? { ...current, security: { ...current.security, activeSessions: current.security.activeSessions.filter((session) => session.current) } } : current; setSettings(keepCurrentSession); setSaved(keepCurrentSession); showNotice("نشست‌های دیگر با موفقیت بسته شدند."); } else { await settingsService.resetDemoData(); showNotice("داده‌های آزمایشی پاک‌سازی شدند."); } setConfirmAction(null); };
  return <><div className="grid items-start gap-4 lg:grid-cols-[minmax(0,1fr)_220px]"><main><SettingsSections settings={settings} onChange={(value) => { setSettings(value); setErrors({}); }} errors={errors} onEnableTwoFactor={() => { setSettings({ ...settings, security: { ...settings.security, twoFactorEnabled: true } }); showNotice("احراز هویت دو مرحله‌ای در نسخه نمایشی فعال شد."); }} onSignOutSessions={() => setConfirmAction("sessions")} onResetDemo={() => setConfirmAction("reset")}/><div className={`sticky bottom-3 z-30 mt-4 flex flex-col gap-3 rounded-(--radius) border p-3 shadow-[0_10px_30px_rgba(23,38,48,.12)] sm:flex-row sm:items-center ${dirty ? "border-(--border-strong) bg-(--accent-soft)" : "border-(--border) bg-white"}`}><p className="ml-auto flex items-center gap-2 text-[12px] font-bold text-(--text-secondary)">{dirty ? <><span className="size-2 rounded-full bg-(--warning)"/> تغییرات ذخیره‌نشده دارید</> : <><Check size={13} className="text-(--brand-teal)"/> همه تغییرات ذخیره شده‌اند</>}</p><button type="button" onClick={() => { if (saved) { setSettings(saved); setErrors({}); } }} disabled={!dirty || saving} className="h-10 rounded-(--radius-sm) border border-(--border) bg-white px-4 text-[13px] font-bold text-(--text-secondary) disabled:opacity-40">لغو تغییرات</button><button type="button" onClick={save} disabled={!dirty || saving} className="flex h-10 items-center justify-center gap-2 rounded-(--radius-sm) bg-(--brand-navy) px-4 text-[13px] font-bold text-white disabled:cursor-not-allowed disabled:opacity-45">{saving ? <LoaderCircle size={14} className="animate-spin"/> : <Save size={14}/>} {saving ? "در حال ذخیره..." : "ذخیره تغییرات"}</button></div></main><SettingsNavigation active={active} onChange={selectSection}/></div><SettingsConfirmDialog action={confirmAction} onCancel={() => setConfirmAction(null)} onConfirm={confirmDanger}/><UnsavedChangesDialog href={pendingHref} onStay={() => setPendingHref(null)} onLeave={() => { const href = pendingHref; setPendingHref(null); if (href) router.push(href); }}/>{notice && <div role="status" className="fixed bottom-5 left-5 z-[100] rounded-(--radius-sm) bg-(--brand-navy) px-4 py-3 text-[13px] font-bold text-white shadow-[0_10px_30px_rgba(16,35,49,.2)]">{notice}</div>}</>;
}
