import { ArticleCardSkeleton } from "@/components/skeletons/article-card-skeleton";
import { NewsletterSkeleton, SectionHeadingSkeleton } from "@/components/skeletons/public-shared-skeletons";
import { LoadingStatus, Skeleton } from "@/components/ui/skeleton";

const lineWidths = ["100%", "94%", "98%", "76%"];

function ParagraphSkeleton({ lines = 4 }: { lines?: number }) {
  return <div className="my-7 space-y-3.5">{Array.from({ length: lines }, (_, index) => <Skeleton key={index} className="h-4 rounded" style={{ width: lineWidths[index % lineWidths.length] }}/>)}</div>;
}

export function ArticleDetailSkeleton() {
  return <LoadingStatus label="در حال بارگذاری مقاله" className="public-site" >
    <main id="main-content">
      <header className="mx-auto max-w-5xl px-4 pb-8 pt-10 text-center md:px-7 md:pb-10 md:pt-14"><Skeleton className="mx-auto h-4 w-24 rounded"/><Skeleton className="mx-auto mt-5 h-10 max-w-4xl rounded sm:h-12"/><Skeleton className="mx-auto mt-3 h-10 w-3/4 max-w-3xl rounded sm:h-12"/><div className="mx-auto mt-6 max-w-3xl space-y-2"><Skeleton className="h-3.5 w-full rounded"/><Skeleton className="mx-auto h-3.5 w-4/5 rounded"/></div><div className="mt-7 flex flex-wrap items-center justify-center gap-3"><Skeleton className="size-10 rounded-full"/><Skeleton className="h-3 w-36 rounded"/><Skeleton className="h-3 w-20 rounded"/><Skeleton className="h-3 w-24 rounded"/><Skeleton className="h-3 w-20 rounded"/></div></header>
      <figure className="mx-auto max-w-6xl px-4 md:px-7"><Skeleton className="aspect-16/8 w-full rounded-(--radius-lg)"/><Skeleton className="mt-2 mr-auto h-2.5 w-40 rounded"/></figure>
      <div className="mx-auto grid max-w-6xl gap-8 px-4 py-10 md:px-7 md:py-14 xl:grid-cols-[160px_minmax(0,720px)_110px]"><aside className="hidden xl:block"><div className="sticky top-28 space-y-3 border-r border-(--border-strong) pr-4"><Skeleton className="mb-5 h-4 w-24 rounded"/>{Array.from({ length: 6 }, (_, index) => <Skeleton key={index} className="h-3 rounded" style={{ width: index % 2 ? "82%" : "100%" }}/>)}</div></aside><div className="min-w-0"><div className="mb-8 rounded-(--radius) border border-(--border-strong) bg-white p-4 xl:hidden"><Skeleton className="h-4 w-28 rounded"/></div><article><ParagraphSkeleton/><Skeleton className="mt-11 h-7 w-2/3 rounded"/><ParagraphSkeleton lines={5}/><div className="my-8 border-r-3 border-(--brand-teal) bg-(--surface-muted) px-5 py-5"><Skeleton className="h-4 w-full rounded"/><Skeleton className="mt-3 h-4 w-4/5 rounded"/></div><Skeleton className="mt-11 h-6 w-1/2 rounded"/><ParagraphSkeleton lines={4}/><div className="my-8 rounded-(--radius) bg-(--public-ink) p-5"><Skeleton className="h-3 w-28 rounded bg-white/14"/>{Array.from({ length: 5 }, (_, index) => <Skeleton key={index} className="mt-3 h-3 rounded bg-white/12" style={{ width: index === 4 ? "62%" : `${88 - index * 3}%` }}/>)}</div><Skeleton className="my-9 aspect-16/9 w-full rounded-(--radius)"/><ParagraphSkeleton lines={4}/><div className="mt-10 flex gap-2 border-t border-(--border-strong) pt-6">{Array.from({ length: 4 }, (_, index) => <Skeleton key={index} className="h-11 w-20 rounded-full"/>)}</div></article><section className="mt-12 rounded-(--radius) border border-(--border-strong) bg-white p-5 sm:flex sm:items-center sm:gap-5 sm:p-6"><Skeleton className="size-18 shrink-0 rounded-full"/><div className="mt-4 flex-1 space-y-3 sm:mt-0"><Skeleton className="h-3 w-24 rounded"/><Skeleton className="h-5 w-32 rounded"/><Skeleton className="h-3 w-44 rounded"/><Skeleton className="h-3 w-full rounded"/><Skeleton className="h-3 w-4/5 rounded"/></div><Skeleton className="mt-4 h-10 w-36 rounded-(--radius-sm) sm:mt-0"/></section></div><aside className="hidden xl:block"><Skeleton className="mx-auto h-3 w-20 rounded"/><div className="mt-4 flex flex-col items-center gap-2">{Array.from({ length: 3 }, (_, index) => <Skeleton key={index} className="size-10 rounded-full"/>)}</div></aside></div>
      <section className="mx-auto max-w-3xl px-4 py-14 md:px-7 md:py-18"><SectionHeadingSkeleton action={false}/><div className="mt-7 space-y-6">{Array.from({ length: 2 }, (_, index) => <article key={index} className="flex gap-3 border-b border-(--border-strong) pb-6"><Skeleton className="size-11 shrink-0 rounded-full"/><div className="flex-1 space-y-3"><Skeleton className="h-3.5 w-28 rounded"/><Skeleton className="h-2.5 w-20 rounded"/><Skeleton className="h-3.5 w-full rounded"/><Skeleton className="h-3.5 w-4/5 rounded"/></div></article>)}</div><div className="mt-12 rounded-[20px] border border-(--border) bg-white p-5 sm:p-7"><Skeleton className="h-5 w-44 rounded"/><Skeleton className="mt-3 h-3 w-3/4 rounded"/><div className="mt-6 grid gap-4 sm:grid-cols-2"><Skeleton className="h-18 rounded-(--radius-sm)"/><Skeleton className="h-18 rounded-(--radius-sm)"/></div><Skeleton className="mt-4 h-36 rounded-(--radius-sm)"/><Skeleton className="mt-5 mr-auto h-11 w-32 rounded-full"/></div></section>
      <section className="border-y border-(--border-strong) bg-(--surface-muted)"><div className="mx-auto max-w-360 px-4 py-12 md:px-7 md:py-16"><Skeleton className="h-3 w-24 rounded"/><Skeleton className="mt-3 h-6 w-44 rounded"/><div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{Array.from({ length: 3 }, (_, index) => <ArticleCardSkeleton key={index}/>)}</div></div></section>
      <div className="pt-14"><NewsletterSkeleton/></div>
    </main>
  </LoadingStatus>;
}
