import { LoadingStatus, Skeleton } from "@/components/ui/skeleton";

export function DashboardSkeleton() {
  return <LoadingStatus label="در حال بارگذاری داشبورد" className="dashboard-shell min-h-screen bg-(--background)" >
    <aside className="fixed inset-y-0 right-0 z-40 hidden w-67 flex-col bg-(--brand-navy) px-4 py-5 lg:flex" aria-hidden="true"><div className="flex items-center gap-3 px-2"><Skeleton className="size-11 rounded-(--radius) bg-white/15"/><div className="space-y-2"><Skeleton className="h-4 w-20 rounded bg-white/18"/><Skeleton className="h-2.5 w-28 rounded bg-white/10"/></div></div><Skeleton className="mt-10 h-3 w-24 rounded bg-white/10"/><div className="mt-4 space-y-2">{Array.from({ length: 8 }, (_, index) => <Skeleton key={index} className={`h-11 w-full rounded-(--radius-sm) ${index === 0 ? "bg-white/16" : "bg-white/8"}`}/>)}</div><div className="mt-auto flex items-center gap-3 border-t border-white/10 pt-5"><Skeleton className="size-10 rounded-full bg-white/15"/><div className="flex-1 space-y-2"><Skeleton className="h-3 w-24 rounded bg-white/16"/><Skeleton className="h-2.5 w-14 rounded bg-white/10"/></div></div></aside>
    <div className="lg:mr-67">
      <header className="sticky top-0 z-30 flex h-19 items-center gap-3 border-b border-(--border) bg-white px-4 md:px-7 lg:px-8"><Skeleton className="size-10 rounded-(--radius-sm) lg:hidden"/><div className="min-w-0 flex-1 space-y-2"><Skeleton className="h-4 w-32 rounded"/><Skeleton className="hidden h-3 w-40 rounded sm:block"/></div><Skeleton className="hidden h-11 w-full max-w-92 rounded-(--radius-sm) md:block"/><Skeleton className="size-10 rounded-(--radius-sm) md:hidden"/><Skeleton className="hidden h-10 w-28 rounded-(--radius-sm) sm:block"/><Skeleton className="size-10 rounded-(--radius-sm)"/><Skeleton className="h-10 w-14 rounded-full"/></header>
      <main className="mx-auto max-w-380 p-4 md:p-7 lg:p-8">
        <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div className="space-y-3"><Skeleton className="h-7 w-44 rounded"/><Skeleton className="h-3 w-60 max-w-[75vw] rounded"/></div><Skeleton className="h-3 w-40 rounded"/></div>
        <section className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 4 }, (_, index) => <article key={index} className="h-37 rounded-(--radius) border border-(--border) bg-white p-4 sm:p-5"><div className="flex items-start justify-between"><div className="space-y-4"><Skeleton className="h-3 w-24 rounded"/><Skeleton className="h-10 w-20 rounded"/></div><Skeleton className="size-10 rounded-(--radius)"/></div><Skeleton className="mt-4 h-3 w-32 rounded"/></article>)}</section>
        <div className="mt-4 grid grid-cols-1 gap-4 lg:grid-cols-3"><section className="min-h-109 rounded-(--radius) border border-(--border) bg-white p-4 sm:p-6 lg:col-span-2"><div className="flex items-start justify-between gap-4"><div className="space-y-2"><Skeleton className="h-4 w-36 rounded"/><Skeleton className="h-3 w-44 rounded"/></div><Skeleton className="h-12 w-44 rounded-(--radius-sm)"/></div><div className="mt-6 flex items-end gap-3"><Skeleton className="h-10 w-28 rounded"/><Skeleton className="h-7 w-16 rounded-md"/></div><div className="relative mt-6 h-57.5 overflow-hidden">{Array.from({ length: 5 }, (_, index) => <span key={index} className="absolute inset-x-0 border-t border-dashed border-(--border-subtle)" style={{ top: `${index * 25}%` }}/>) }<Skeleton className="absolute bottom-4 right-0 h-[42%] w-full rounded-t-[55%] opacity-70"/><div className="absolute inset-x-0 bottom-0 flex justify-between"><Skeleton className="h-2.5 w-12 rounded"/><Skeleton className="h-2.5 w-12 rounded"/><Skeleton className="h-2.5 w-12 rounded"/><Skeleton className="h-2.5 w-12 rounded"/></div></div><Skeleton className="mt-4 h-3 w-64 max-w-full rounded"/></section><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-1"><section className="rounded-(--radius) border border-(--border) bg-white p-4 sm:p-5"><Skeleton className="h-4 w-24 rounded"/><Skeleton className="mt-2 h-3 w-36 rounded"/><div className="mt-4 grid grid-cols-2 gap-2 xl:grid-cols-1">{Array.from({ length: 4 }, (_, index) => <Skeleton key={index} className="h-12 w-full rounded-(--radius-sm)"/>)}</div></section><section className="rounded-(--radius) border border-(--border) bg-white p-4 sm:p-5"><div className="flex justify-between"><div className="space-y-2"><Skeleton className="h-4 w-28 rounded"/><Skeleton className="h-3 w-36 rounded"/></div><Skeleton className="size-2 rounded-full"/></div><div className="mt-5 space-y-5">{Array.from({ length: 4 }, (_, index) => <div key={index} className="relative flex gap-3"><Skeleton className="size-10 shrink-0 rounded-full"/><div className="flex-1 space-y-2 pt-1"><Skeleton className="h-3 w-full rounded"/><Skeleton className="h-3 w-4/5 rounded"/><Skeleton className="h-2.5 w-16 rounded"/></div></div>)}</div></section></div></div>
        <section className="mt-4 overflow-hidden rounded-(--radius) border border-(--border) bg-white"><div className="flex items-center justify-between border-b border-(--border) px-4 py-4 sm:px-6"><div className="space-y-2"><Skeleton className="h-4 w-24 rounded"/><Skeleton className="h-3 w-40 rounded"/></div><Skeleton className="h-10 w-24 rounded-lg"/></div><div className="hidden md:block"><div className="grid h-12 grid-cols-[2fr_1.2fr_1fr_1fr_.7fr_1fr_40px] items-center gap-4 bg-(--surface-subtle) px-6">{Array.from({ length: 7 }, (_, index) => <Skeleton key={index} className="h-3 w-full rounded"/>)}</div><div className="divide-y divide-(--border-subtle)">{Array.from({ length: 6 }, (_, row) => <div key={row} className="grid h-17 grid-cols-[2fr_1.2fr_1fr_1fr_.7fr_1fr_40px] items-center gap-4 px-6"><Skeleton className="h-3 w-[90%] rounded"/><div className="flex items-center gap-2"><Skeleton className="size-7 shrink-0 rounded-full"/><Skeleton className="h-3 flex-1 rounded"/></div><Skeleton className="h-3 w-3/4 rounded"/><Skeleton className="h-6 w-20 rounded-full"/><Skeleton className="h-3 w-12 rounded"/><Skeleton className="h-3 w-20 rounded"/><Skeleton className="size-10 rounded-lg"/></div>)}</div></div><div className="divide-y divide-(--border-subtle) md:hidden">{Array.from({ length: 5 }, (_, row) => <article key={row} className="p-4"><div className="flex items-start justify-between gap-3"><div className="flex-1 space-y-3"><Skeleton className="h-3.5 w-full rounded"/><Skeleton className="h-3.5 w-4/5 rounded"/><div className="flex gap-2"><Skeleton className="h-6 w-20 rounded-full"/><Skeleton className="h-3 w-16 rounded"/></div></div><Skeleton className="size-10 rounded-lg"/></div><div className="mt-4 flex justify-between"><Skeleton className="h-2.5 w-20 rounded"/><Skeleton className="h-2.5 w-24 rounded"/></div></article>)}</div></section>
        <div className="mt-6 flex justify-between border-t border-(--border) pt-5"><Skeleton className="h-3 w-44 rounded"/><Skeleton className="h-3 w-16 rounded"/></div>
      </main>
    </div>
  </LoadingStatus>;
}
