import { ArticleCardSkeleton } from "@/components/skeletons/article-card-skeleton";
import { AuthorCardSkeleton, CategoryCardSkeleton, NewsletterSkeleton, SectionHeadingSkeleton } from "@/components/skeletons/public-shared-skeletons";
import { LoadingStatus, Skeleton } from "@/components/ui/skeleton";

export function HomePageSkeleton() {
  return <LoadingStatus label="در حال بارگذاری صفحه اصلی" className="public-site" >
    <main id="main-content">
      <section className="border-b border-(--border) bg-(--public-paper)"><div className="mx-auto max-w-360 px-4 pb-10 pt-8 md:px-7 md:pb-16 md:pt-12"><SectionHeadingSkeleton/><div className="mt-7 grid gap-5 lg:grid-cols-[minmax(0,1.8fr)_minmax(320px,.82fr)]"><ArticleCardSkeleton variant="featured"/><aside className="flex flex-col justify-between gap-5 rounded-[22px] border border-(--border) bg-white/72 p-5 sm:p-6">{Array.from({ length: 3 }, (_, index) => <ArticleCardSkeleton key={index} variant="compact"/>)}</aside></div></div></section>
      <section className="border-b border-(--border) bg-white"><div className="mx-auto flex max-w-360 items-center gap-4 overflow-hidden px-4 py-4 md:px-7"><Skeleton className="h-4 w-24 shrink-0 rounded"/><Skeleton className="h-5 w-px shrink-0"/>{Array.from({ length: 7 }, (_, index) => <Skeleton key={index} className="h-10 w-24 shrink-0 rounded-full"/>)}</div></section>
      <section className="mx-auto max-w-360 px-4 py-14 md:px-7 md:py-20"><SectionHeadingSkeleton/><div className="mt-9 grid gap-x-7 gap-y-12 sm:grid-cols-2 lg:grid-cols-3">{Array.from({ length: 6 }, (_, index) => <ArticleCardSkeleton key={index}/>)}</div></section>
      <section className="bg-(--public-ink)"><div className="mx-auto grid max-w-360 lg:grid-cols-[1fr_1.08fr]"><Skeleton className="min-h-84 bg-white/10 lg:min-h-128"/><div className="flex items-center px-5 py-12 sm:px-10 lg:px-14"><div className="w-full max-w-xl"><Skeleton className="size-10 rounded-full bg-white/15"/><Skeleton className="mt-5 h-3 w-28 rounded bg-white/14"/><Skeleton className="mt-4 h-10 w-full rounded bg-white/18"/><Skeleton className="mt-3 h-10 w-4/5 rounded bg-white/18"/><div className="mt-5 space-y-2"><Skeleton className="h-3.5 w-full rounded bg-white/12"/><Skeleton className="h-3.5 w-3/4 rounded bg-white/12"/></div><Skeleton className="mt-7 h-12 w-36 rounded-full bg-white/16"/></div></div></div></section>
      <section className="bg-white"><div className="mx-auto max-w-360 px-4 py-14 md:px-7 md:py-20"><SectionHeadingSkeleton/><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Array.from({ length: 8 }, (_, index) => <CategoryCardSkeleton key={index} featured={index === 0}/>)}</div></div></section>
      <section className="bg-(--public-paper-deep)"><div className="mx-auto max-w-360 px-4 py-14 md:px-7 md:py-20"><SectionHeadingSkeleton action={false}/><div className="mt-9 grid gap-8 lg:grid-cols-[1.08fr_.92fr]"><article className="overflow-hidden rounded-[22px] bg-white"><Skeleton className="aspect-16/9 w-full"/><div className="p-6 sm:p-7"><Skeleton className="h-3 w-24 rounded"/><Skeleton className="mt-4 h-6 w-full rounded"/><Skeleton className="mt-2 h-6 w-3/4 rounded"/><Skeleton className="mt-4 h-3.5 w-full rounded"/><Skeleton className="mt-2 h-3.5 w-4/5 rounded"/><Skeleton className="mt-5 h-11 w-28 rounded-full"/></div></article><div className="divide-y divide-(--border-strong) border-y border-(--border-strong)">{Array.from({ length: 4 }, (_, index) => <div key={index} className="grid grid-cols-[54px_minmax(0,1fr)] gap-4 py-5"><Skeleton className="h-10 w-10 rounded"/><div className="space-y-3"><Skeleton className="h-3 w-20 rounded"/><Skeleton className="h-4 w-full rounded"/><Skeleton className="h-4 w-4/5 rounded"/><Skeleton className="h-3 w-32 rounded"/></div></div>)}</div></div></div></section>
      <section className="mx-auto max-w-360 px-4 py-14 md:px-7 md:py-20"><SectionHeadingSkeleton/><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{Array.from({ length: 5 }, (_, index) => <AuthorCardSkeleton key={index}/>)}</div></section>
      <NewsletterSkeleton/>
    </main>
  </LoadingStatus>;
}
