"use client";

import Link from "next/link";
import { Copy, Eye, FileText, MoreHorizontal, PenLine, Power, Trash2 } from "lucide-react";
import { roleLabels, type Author } from "@/lib/authors-data";

export function AuthorCard({ author, onPreview, onCopy, onToggle, onDelete }: { author: Author; onPreview: () => void; onCopy: () => void; onToggle: () => void; onDelete: () => void }) {
  const number = new Intl.NumberFormat("fa-IR");
  return <article className="group relative rounded-(--radius) border border-(--border) bg-white p-5 transition-all hover:-translate-y-0.5 hover:border-(--border-strong) hover:shadow-[0_10px_30px_rgba(23,38,48,.06)]">
    <div className="flex items-start gap-3">
      <button type="button" onClick={onPreview} aria-label={`مشاهده پروفایل ${author.name}`} className={`grid size-12 shrink-0 place-items-center rounded-full text-sm font-bold ${author.avatarColor}`}>{author.avatar ? <span className="size-full rounded-full bg-cover bg-center" style={{ backgroundImage: `url(${author.avatar})` }} /> : author.initials}</button>
      <div className="min-w-0 flex-1"><button type="button" onClick={onPreview} className="block max-w-full truncate text-right text-[13px] font-bold text-(--text-strong) hover:text-(--accent)">{author.name}</button><p dir="ltr" className="mt-1 text-right text-[12px] text-(--text-muted)">@{author.username}</p><span className="mt-2 inline-flex rounded-md bg-(--surface-muted) px-2 py-1 text-[12px] font-bold text-(--text-secondary)">{roleLabels[author.role]}</span></div>
      <details className="relative"><summary className="grid size-10 cursor-pointer list-none place-items-center rounded-lg text-(--text-muted) hover:bg-(--surface-muted) [&::-webkit-details-marker]:hidden" aria-label={`عملیات ${author.name}`}><MoreHorizontal size={18} /></summary><div className="absolute left-0 top-9 z-20 w-44 rounded-(--radius) border border-(--border) bg-white p-1.5 shadow-[0_12px_30px_rgba(23,38,48,.13)]"><button type="button" onClick={onPreview} className="flex h-10 w-full items-center gap-2 rounded-md px-2.5 text-[13px] text-(--text-secondary) hover:bg-(--surface-muted)"><Eye size={14} /> مشاهده پروفایل</button><Link href={`/admin/authors/${author.id}/edit`} className="flex h-10 items-center gap-2 rounded-md px-2.5 text-[13px] text-(--text-secondary) hover:bg-(--surface-muted)"><PenLine size={14} /> ویرایش</Link><button type="button" onClick={onCopy} className="flex h-10 w-full items-center gap-2 rounded-md px-2.5 text-[13px] text-(--text-secondary) hover:bg-(--surface-muted)"><Copy size={14} /> کپی لینک</button><button type="button" onClick={onToggle} className="flex h-10 w-full items-center gap-2 rounded-md px-2.5 text-[13px] text-(--text-secondary) hover:bg-(--surface-muted)"><Power size={14} /> {author.status === "active" ? "غیرفعال کردن" : "فعال کردن"}</button><div className="my-1 border-t border-(--border-subtle)" /><button type="button" onClick={onDelete} className="flex h-10 w-full items-center gap-2 rounded-md px-2.5 text-[13px] font-bold text-(--danger) hover:bg-(--danger-soft)"><Trash2 size={14} /> حذف</button></div></details>
    </div>
    <p className="mt-4 line-clamp-2 min-h-11 text-[13px] leading-[1.9] text-(--text-secondary)">{author.bio}</p>
    <div className="mt-4 grid grid-cols-2 divide-x divide-x-reverse divide-[#e8ebed] rounded-(--radius-sm) bg-(--surface-subtle) py-3"><div className="px-3"><strong className="block text-sm text-(--text-strong)">{number.format(author.articleCount)}</strong><span className="mt-1 flex items-center gap-1 text-[14px] text-(--text-muted)"><FileText size={10} /> مقاله</span></div><div className="px-3"><strong className="block text-sm text-(--text-strong)">{number.format(author.totalViews)}</strong><span className="mt-1 block text-[14px] text-(--text-muted)">مجموع بازدید</span></div></div>
    <div className="mt-4 flex items-center justify-between"><span className={`inline-flex items-center gap-1.5 text-[12px] font-bold ${author.status === "active" ? "text-(--brand-teal)" : "text-(--text-muted)"}`}><span className={`size-1.5 rounded-full ${author.status === "active" ? "bg-(--brand-teal)" : "bg-(--border-strong)"}`} />{author.status === "active" ? "فعال" : "غیرفعال"}</span><span className="text-[14px] text-(--text-muted)">عضویت: {author.joinedLabel}</span></div>
  </article>;
}

